# Generated by Django 4.2.29 on 2026-03-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('shield', 'Shield/Security'), ('star', 'Star/Quality'), ('clock', 'Clock/Time'), ('award', 'Award/Trophy'), ('heart', 'Heart/Trust'), ('users', 'Users/Team'), ('check', 'Check/Verified'), ('support', 'Support/Help')], default='shield', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'why_choose_us',
                'ordering': ['order'],
            },
        ),
    ]
