# Generated by Django 4.2.28 on 2026-07-05 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=200)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('alternate_phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, db_index=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('district', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('project_type', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Bangalow', 'Bangalow'), ('Semi-Bangalow', 'Semi-Bangalow')], db_index=True, max_length=50)),
                ('house_style', models.CharField(blank=True, default='', max_length=150)),
                ('number_of_floors', models.PositiveIntegerField(default=0)),
                ('land_size', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('built_up_area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_budget', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=14, null=True)),
                ('construction_status', models.CharField(choices=[('New Lead', 'New Lead'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('On Hold', 'On Hold')], db_index=True, default='New Lead', max_length=50)),
                ('project_start_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('customer_source', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_customers', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_customers_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_followups_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='crm.customer')),
            ],
            options={
                'db_table': 'crm_follow_ups',
                'ordering': ['-follow_up_date'],
            },
        ),
        migrations.CreateModel(
            name='CustomerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='crm/customer_images/')),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_images', to='crm.customer')),
            ],
            options={
                'db_table': 'crm_customer_images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('blueprint', 'Blueprint PDF'), ('agreement', 'Agreement PDF'), ('other', 'Other Document')], default='other', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('file', models.FileField(upload_to='crm/customer_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.customer')),
            ],
            options={
                'db_table': 'crm_customer_documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
