# Generated by Django 4.2.28 on 2026-04-17 06:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'OTPVerification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='OTPVerifica_email_947bdc_idx'), models.Index(fields=['created_at'], name='OTPVerifica_created_6ea93c_idx'), models.Index(fields=['is_verified'], name='OTPVerifica_is_veri_5e4fa7_idx')],
            },
        ),
    ]
