# Generated by Django 4.2.29 on 2026-05-26 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_pendingsignup'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PasswordResetToken',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='PasswordRes_token_9b53fd_idx'), models.Index(fields=['user'], name='PasswordRes_user_id_eaa91f_idx'), models.Index(fields=['expires_at'], name='PasswordRes_expires_864f8a_idx'), models.Index(fields=['is_used'], name='PasswordRes_is_used_26eaf1_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'EmailVerificationToken',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='EmailVerifi_token_d9d073_idx'), models.Index(fields=['user'], name='EmailVerifi_user_id_2a7032_idx'), models.Index(fields=['expires_at'], name='EmailVerifi_expires_20f4b6_idx'), models.Index(fields=['is_used'], name='EmailVerifi_is_used_c819fe_idx')],
            },
        ),
    ]
