# Generated by Django 4.2.28 on 2026-04-17 09:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_alter_property_house_type_alter_property_size_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_user_property_favorite',
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'property')},
        ),
    ]
