# Generated by Django 4.2.28 on 2026-03-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellrequest',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='sell_request_images/'),
        ),
    ]
