# Generated by Django 4.2.29 on 2026-03-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_sellrequest_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='inquiry_type',
            field=models.CharField(choices=[('construction', 'Construction'), ('property', 'Property'), ('general', 'General'), ('sell', 'Sell'), ('build_property', 'Build Property')], default='general', max_length=20),
        ),
    ]
