# Generated by Django 4.2.29 on 2026-03-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0003_alter_inquiry_email_alter_inquiry_inquiry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inquiry_images/'),
        ),
    ]
