# Generated by Django 4.2.29 on 2026-03-30 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0004_inquiry_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sell_request_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sell_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_images', to='inquiries.sellrequest')),
            ],
            options={
                'db_table': 'sell_request_images',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
