# Generated by Django 4.2.28 on 2026-02-25 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('location', models.CharField(max_length=200)),
                ('land_size', models.DecimalField(decimal_places=2, help_text='Land size in sq ft', max_digits=10)),
                ('built_area', models.DecimalField(blank=True, decimal_places=2, help_text='Built area in sq ft', max_digits=10, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('road_access', models.TextField(blank=True, help_text='Road access description')),
                ('parking', models.BooleanField(default=False, help_text='Parking availability')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold'), ('Featured', 'Featured')], default='Available', max_length=20)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'db_table': 'property_images',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
    ]
