# Generated by Django 4.2.28 on 2026-02-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='road_access',
            field=models.BooleanField(default=False, help_text='Road access availability'),
        ),
    ]
