# Generated by Django 4.2.28 on 2026-03-06 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0002_alter_property_road_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='built_area',
        ),
        migrations.RemoveField(
            model_name='property',
            name='land_size',
        ),
        migrations.RemoveField(
            model_name='property',
            name='parking',
        ),
        migrations.RemoveField(
            model_name='property',
            name='road_access',
        ),
        migrations.AddField(
            model_name='property',
            name='house_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], default='Buy', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Size of the property', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='size_unit',
            field=models.CharField(choices=[('Aana', 'Aana'), ('Sqft', 'Sqft')], default='Sqft', max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in NPR', max_digits=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
