# Generated by Django 4.2.29 on 2026-03-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_remove_property_built_area_remove_property_land_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='built_area',
            field=models.CharField(blank=True, help_text='Built area (e.g., 1500 sqft)', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='land_size',
            field=models.CharField(blank=True, help_text='Land size (e.g., 5 Aana)', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='parking',
            field=models.BooleanField(default=False, help_text='Parking available'),
        ),
        migrations.AddField(
            model_name='property',
            name='road_access',
            field=models.CharField(blank=True, help_text='Road access description', max_length=200),
        ),
    ]
