# Generated by Django 4.2.29 on 2026-03-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_built_area_property_land_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show on homepage as featured property'),
        ),
    ]
