# Generated by Django 4.2.29 on 2026-03-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.IntegerField(default=0, help_text='Area in sqft'),
        ),
        migrations.AddField(
            model_name='property',
            name='features',
            field=models.JSONField(default=list, help_text='List of features: Pool, Garden, Parking, etc.'),
        ),
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, help_text='Main property image', null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_new',
            field=models.BooleanField(default=False, help_text='Mark as new property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='house_type',
            field=models.CharField(choices=[('Villa', 'Villa'), ('Apartment', 'Apartment'), ('Penthouse', 'Penthouse'), ('Townhouse', 'Townhouse'), ('Duplex', 'Duplex'), ('Studio', 'Studio'), ('Cottage', 'Cottage'), ('Mansion', 'Mansion'), ('House', 'House')], default='House', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold'), ('Pending', 'Pending')], default='Available', max_length=20),
        ),
    ]
