# Generated by Django 4.2.29 on 2026-03-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_property_location_alter_property_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='build',
            field=models.IntegerField(blank=True, help_text='Year built', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.IntegerField(blank=True, default=0, help_text='Area in sqft', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='built_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Built area in sqft', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='land_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Land size in sqft', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='road_access',
            field=models.BooleanField(default=False, help_text='Road access available'),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
