# Generated by Django 4.2.29 on 2026-03-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_property_build_alter_property_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Project name', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('location', models.CharField(help_text='Location in Kathmandu/Tokha', max_length=200)),
                ('plot_size', models.CharField(help_text='Plot size e.g. 5 Aana, 10 Ropani', max_length=100)),
                ('estimated_budget', models.DecimalField(decimal_places=2, help_text='Estimated budget in NPR', max_digits=15)),
                ('build_type', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Mixed', 'Mixed')], default='Residential', max_length=20)),
                ('status', models.CharField(choices=[('Planning', 'Planning'), ('In Progress', 'In Progress'), ('Ready to Build', 'Ready to Build')], default='Planning', max_length=20)),
                ('floors', models.IntegerField(default=1, help_text='Number of floors')),
                ('parking_spaces', models.IntegerField(default=0, help_text='Number of parking spaces')),
                ('design_style', models.CharField(choices=[('Modern', 'Modern'), ('Traditional', 'Traditional'), ('Contemporary', 'Contemporary'), ('Minimalist', 'Minimalist')], default='Modern', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Project description')),
                ('image', models.ImageField(blank=True, help_text='Project image', null=True, upload_to='build_projects/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'build_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='property',
            name='house_type',
            field=models.CharField(choices=[('Villa', 'Villa'), ('Apartment', 'Apartment'), ('Penthouse', 'Penthouse'), ('Townhouse', 'Townhouse'), ('Duplex', 'Duplex'), ('Studio', 'Studio'), ('Cottage', 'Cottage'), ('Mansion', 'Mansion'), ('House', 'House'), ('Buy', 'Buy'), ('Sell', 'Sell')], default='House', max_length=20),
        ),
    ]
