# Generated by Django 4.2.29 on 2026-03-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_buildproject_alter_property_house_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='face_direction',
            field=models.CharField(blank=True, help_text='Face direction: East, West, North, South', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='floors',
            field=models.IntegerField(blank=True, default=1, help_text='Number of floors', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='lalpurja_status',
            field=models.CharField(blank=True, help_text='Lalpurja status: Available, In process, Not available', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='napi_done',
            field=models.CharField(blank=True, help_text='Napi done: Yes, No, In process', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='posted_by_name',
            field=models.CharField(blank=True, help_text='Owner/Agent name', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='posted_by_phone',
            field=models.CharField(blank=True, help_text='Phone number in Nepal format', max_length=20),
        ),
    ]
