# Generated by Django 4.2.29 on 2026-03-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_property_face_direction_property_floors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional title for the video', max_length=200)),
                ('video', models.FileField(help_text='Upload video file', upload_to='property_videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Show this video on the homepage')),
            ],
            options={
                'db_table': 'property_videos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
