# Generated by Django 4.2.28 on 2026-04-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_propertyvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='house_type',
            field=models.CharField(choices=[('Commercial', 'Commercial'), ('Residential', 'Residential'), ('Semi Bangalow', 'Semi Bangalow'), ('Bangalow', 'Bangalow'), ('Villa', 'Villa'), ('Apartment', 'Apartment'), ('Penthouse', 'Penthouse'), ('Townhouse', 'Townhouse'), ('Duplex', 'Duplex'), ('Studio', 'Studio'), ('Cottage', 'Cottage'), ('Mansion', 'Mansion'), ('House', 'House'), ('Land', 'Land')], default='House', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='size_unit',
            field=models.CharField(choices=[('Aana', 'Aana'), ('Sqft', 'Sqft'), ('Ropani', 'Ropani')], default='Sqft', max_length=10),
        ),
    ]
